### ISSUE TITLE
第208页的demo后“我们返回的是 Just(3) 这个 Publisher，而不仅仅只是 Int 的 3。”

### ISSUE THREAD

**Issue by Liaoworking** [onevcat/swift-ui-book-issue#12]
第208页的demo后“我们返回的是 Just(3) 这个 Publisher，而不仅仅只是 Int 的 3。”  Demo里面是Just(-1)。 
  可能是改了数据没有同步到下面的文章中？

**Comment by onevcat** [comment]
已修正，感谢！
