### ISSUE TITLE
图片指示错误（使用 Modifier 描述 Text 及 Button-基本 Modifier）

### ISSUE THREAD

**Issue by beforeold** [onevcat/swift-ui-book-issue#14]
1、这一部分描述 Text 的 modifier 时，对 padding 和 backgroundColor 在图片中的指向互相混淆了

pdf 第28页

2、紧接着在第 30 页的开头处，

> 由 2 导致的在 “+” 文本周围的内层橙色背景并不会包括 padding 的影响

根据上下文，应该是要表达"由 1 导致的...."

**Comment by onevcat** [comment]
已在最新版本中修复，稍后发布。
