### ISSUE TITLE
PDF格式目录跳转有问题

### ISSUE THREAD

**Issue by li-bei** [onevcat/swift-ui-book-issue#17]
目录和内容无法对应上，有很大的偏差。

macOS 10.15.1 Preview app.

测试了一下Swifter Tips这本书没有问题。

**Comment by CoderWeiLee** [comment]
> 目录和内容无法对应上，有很大的偏差。
> 
> macOS 10.15.1 Preview app.
> 
> 测试了一下Swifter Tips这本书没有问题。

本书的源码是在哪边可以看到啊
