### ISSUE TITLE
ForEach(row, id: \.self) 跑不通

### ISSUE THREAD

**Issue by youzi001** [onevcat/swift-ui-book-issue#2]
文中包含ForEach(row, id: \.self) 的地方是否应该改为ForEach(row.identified(by: \.self))

**Comment by onevcat** [comment]
新的 beta 里应该已经没有 `identified(by:)` 了，您用的 Xcode 11 是 beta 几？

**Comment by youzi001** [comment]
Version 11.0 beta (11M336w)  抱歉我以为我是最新版的 我这就去更新
