### ISSUE TITLE
请问下，本书源码是在哪边可以看到

### ISSUE THREAD

**Issue by CoderWeiLee** [onevcat/swift-ui-book-issue#25]
`打开本书源码的2.Hello-SwiftUI文件夹`  ，PDF文件里没有看到，有知道的朋友告诉我一下吗

**Comment by onevcat** [comment]
在购买本书的时候，源码应该是随书一起下载的。如果没有找到的话，可以通过登入 objccn.io 到图书页面https://objccn.io/products/swift-ui/downloads/ 再次下载。

**Comment by CoderWeiLee** [comment]
> 在购买本书的时候，源码应该是随书一起下载的。如果没有找到的话，可以通过登入 objccn.io 到图书页面https://objccn.io/products/swift-ui/downloads/ 再次下载。

谢谢喵大

**Comment by birneysky** [comment]
请问，小专栏购买的 demo 在哪里下载

**Comment by onevcat** [comment]
小专栏版本的最后一章里应该有。

**Comment by birneysky** [comment]
> 小专栏版本的最后一章里应该有。

哦，看到了，谢谢
