### ISSUE TITLE
第三章 `@Published` 代码块勘误

### ISSUE THREAD

**Issue by Desgard** [onevcat/swift-ui-book-issue#28]
![image](https://user-images.githubusercontent.com/7804535/70594408-6c9acb00-1c1b-11ea-8a40-c76f61f3fdb2.png) PDF Page-87

```swift
@Published var history: [CalculatorButtonItem] = []
```

**Comment by Desgard** [comment]
[小专栏版本](https://xiaozhuanlan.com/swift-ui/5016978324)相同问题，pdf 版本是**技术预览版**

**Comment by onevcat** [comment]
感谢！这个问题在最新的 PDF 版本中应该已经修正了。
