### ISSUE TITLE
订阅被取消了

### ISSUE THREAD

**Issue by zhanyongZhang** [onevcat/swift-ui-book-issue#32]
<img width="779" alt="Screen Shot 2019-12-26 at 10 42 00 AM" src="https://user-images.githubusercontent.com/19421248/71454600-78b28b00-27cc-11ea-8225-e7b4e43618b2.png">

**Comment by onevcat** [comment]
Xcode 11.3 里这部分的内存管理的机制又被改了...我会看看怎么处理比较好。感谢！

**Comment by onevcat** [comment]
已经更新，书籍的 1.5 版后重新讨论和改写了这部分内容。
