### ISSUE TITLE
LoginAppCommand 的 Publisher 被 cancel

### ISSUE THREAD

**Issue by anatta-feng** [onevcat/swift-ui-book-issue#36]
![image](https://user-images.githubusercontent.com/20234820/80973557-1e989500-8e52-11ea-9001-fb3fc28ae1e3.png)
![image](https://user-images.githubusercontent.com/20234820/80973571-248e7600-8e52-11ea-941f-995aab42d665.png)

**Comment by onevcat** [comment]
已经在蛮久以前就修复了。可以考虑重新下载一下更新版本。

Ref: #32
