### ISSUE TITLE
请问有无各章后面练习题的参考答案？

### ISSUE THREAD

**Issue by hemincong** [onevcat/swift-ui-book-issue#45]
老师好！《SwiftUI与Combine编程》一书中有源码和各章练习题，请问有无参考答案？譬如在“数据状态和绑定”一章中的第三题（选做）修正计算器模型中的 bug，没有头绪，想在“apply(num: Int) -> CalculatorBrain”函数中修改，但好像都不怎么对。

谢谢老师！

**Comment by hemincong** [comment]
还有第五章的练习题，虽然是做了判断，但不知是不是对的

**Comment by onevcat** [comment]
您好..

老师不敢当。

在第一章介绍里其实就提到了：

> 在每章结束后，我们为读者准备了若干的练习题以及一些挑战项目。挑战项目的内容一般是对于示例 app 的代码不足之处的一些补完任务，为了不限制思路，我们并没有提供标准答案：实践才是检验真理的途径。如果能够完成这些可选内容，相信会对加深理解大有裨益。

因此正如所言，并没有提供答案。不过对于“数据状态和绑定”一章中的第三题，可以给出一点提示：bug 的起因是由于即使是通过 `.equal` 操作得到的结果，反映在 `CalculatorBrain` 上，它和普通通过输入得到的 `.left` case 是没有区别的。如果我们能够区分普通的 `.left` 和通过按下等号得到的 `.left`，我们就可以在接受新的 `digit` 或者 `.op` 的时候做出不同的行为。

一个最直观的想法就是为 `.left` 添加一个额外的参数，来代表它是不是通过 `.equal` 所得到的结果：

```diff
enum CalculatorBrain {
-    case left(String)
+    case left(String, equalResult: Bool)
```

之后，我们就可以对 `apply(num: Int)` 进行修改了：

```swift
private func apply(num: Int) -> CalculatorBrain {
        switch self {
        case .left(let left, let equalResult):
            return equalResult ? .left("\(num)", equalResult: false) : .left(left.apply(num: num), equalResult: false)
```

当然，项目还有其他部分也许要进行修改，之后的操作就都交给您了！

个人建议，您可以在 `CalculatorBrainTests.swift` 里先添加测试用例，这样在进行修改时只需要运行测试就可以快速确认结果，而不需要一遍遍操作 UI。

**Comment by hemincong** [comment]
非常感谢老师提供的思路！
